from enum import Enum


class Categoria(Enum):
    NO_RECONOCIDO = 1
    ENTERO = 2
    REAL = 3
    IDENTIFICADOR = 4
    PALABRA_RESERVADA = 5
    CADENA_CARACTERES = 6
    COMENTARIO_LINEA = 7
    PARENTESIS_APERTURA = 8
    OPERADOR_ARITMETICO = 9
    OPERADOR_RELACIONAL = 10
    OPERADOR_LOGICO = 11
    OPERADOR_INCREMENTO_DECREMENTO = 12
    OPERADOR_ASIGNACION = 13
    SEPARADOR_COMA = 14
    FIN_DE_SENTENCIA = 15
    NUMERO_HEX = 16
    PARENTESIS_CIERRE = 17
    LLAVES_APERTURA = 18
    LLAVES_CIERRE = 19


